spring.application.name=notification
spring.config.import=classpath:env.properties
server.port=${NOTIFICATION_SERVER_PORT}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${NOTIFICATION_KAFKA_GROUP_ID}

# Confluent Security
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.hireflow.notification.event.EmailNotificationEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hireflow.notification.event

hireflow.kafka.topics.notification-email=${NOTIFICATION_EMAIL_TOPIC}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
